# Generated by Django 5.0.6 on 2024-06-28 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_userprofile_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='creationDate',
            field=models.DateField(default=datetime.date(2024, 6, 28)),
        ),
    ]
