# Generated by Django 5.0.6 on 2024-07-03 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_userprofile_nickname_alter_userprofile_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profilePicture',
            new_name='profile_picture',
        ),
    ]
